## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

City_ID         City Country  Max Temp Current Description      Lat  \
0        2      Palauig      PH     83.62          few clouds  15.4350   
1        3       Bonthe      SL     75.60       broken clouds   7.5264   
2        6     Lorengau      PG     80.78     overcast clouds  -2.0226   
3       11  Bandarbeyla      SO     77.92       broken clouds   9.4942   
4       13    Mapiripan      CO     76.60       broken clouds   2.8892   

        Lng   Hotel Name  
0  119.9045      Palauig  
1  -12.5050       Bonthe  
2  147.2712     Lorengau  
3   50.8122  Bandarbeyla  
4  -72.1256    Mapiripán

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
vacation_hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=vacation_hotel_info)
# 4b. Display the figure
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig.add_layer(marker_layer)
# Call the figure 
fig



Figure(layout=FigureLayout(height='420px'))

In [5]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df["City"] == "Waiuku"]
vacation_end = vacation_df.loc[vacation_df["City"] == "Waiuku"]
vacation_stop1 = vacation_df.loc[vacation_df["City"] == "Byron Bay"]
vacation_stop2 = vacation_df.loc[vacation_df["City"] == "Deniliquin"] 
vacation_stop3 = vacation_df.loc[vacation_df["City"] == "Condrington"] 

In [6]:
import numpy as np

In [7]:
vacation_start

City_ID    City Country  Max Temp Current Description    Lat     Lng  \
137      605  Waiuku      NZ     78.98           clear sky -37.25  174.75   

    Hotel Name  
137     Waiuku

In [36]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.

# start location 
loc1 = vacation_start[["Lat", "Lng"]].to_numpy()
start =[]
for i in loc1:
    for u in i:
        start.append(u)
        
# End location
end = start
loc2 = vacation_end[["Lat", "Lng"]].to_numpy()
# end =[]
# for i in loc2:
#     for u in i:
#         end.append(u)
# stop 1 location
loc3 = vacation_stop1[["Lat", "Lng"]].to_numpy()
stop1 =[]
for i in loc3:
    for u in i:
        stop1.append(u)
        
# stop 2 location 
loc4 = vacation_stop2[["Lat", "Lng"]].to_numpy()
stop2 =[]
for i in loc4:
    for u in i:
        stop2.append(u)
        
# stop 3 location 
loc5 = vacation_stop3[["Lat", "Lng"]].to_numpy()
stop3=[]
for i in loc5:
    for u in i:
        stop3.append(u)
print(start)
print(end)
print(loc1)
print(loc2)
print(loc3)
print(loc4)

[-37.25, 174.75]
[-37.25, 174.75]
[[-37.25 174.75]]
[[-37.25 174.75]]
[[-28.65   153.6167]]
[[-35.5333 144.9667]]


In [37]:
len(stop1)

2

In [38]:
import gmaps.datasets

In [43]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".


In [40]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_end,vacation_stop1,vacation_stop2,vacation_stop3],ignore_index=True)
itinerary_df

City_ID        City Country  Max Temp Current Description      Lat  \
0      605      Waiuku      NZ     78.98           clear sky -37.2500   
1      605      Waiuku      NZ     78.98           clear sky -37.2500   
2      298   Byron Bay      AU     77.11       moderate rain -28.6500   
3      626  Deniliquin      AU     79.48       broken clouds -35.5333   

        Lng  Hotel Name  
0  174.7500      Waiuku  
1  174.7500      Waiuku  
2  153.6167   Byron Bay  
3  144.9667  Deniliquin

In [41]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [42]:
# 11a. Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))