## Deliverable 3. Create a Travel Itinerary Map.

In [24]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [25]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("WeatherPy_vacation.csv")
vacation_df.head()

City_ID            City Country  Max Temp Current Description      Lat  \
0        2         Palauig      PH     83.62          few clouds  15.4350   
1        3          Bonthe      SL     75.60       broken clouds   7.5264   
2        6        Lorengau      PG     80.78     overcast clouds  -2.0226   
3        9  Port Elizabeth      ZA     70.11          few clouds -33.9180   
4       11     Bandarbeyla      SO     77.92       broken clouds   9.4942   

        Lng   Hotel Name  
0  119.9045      Palauig  
1  -12.5050       Bonthe  
2  147.2712     Lorengau  
3   25.5701     Gqeberha  
4   50.8122  Bandarbeyla

In [26]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
vacation_hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [27]:
# 4a. Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=vacation_hotel_info)
# 4b. Display the figure
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig.add_layer(marker_layer)
# Call the figure 
fig



Figure(layout=FigureLayout(height='420px'))

In [28]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df["City"] == "Port Lincoln"]
vacation_end = vacation_df.loc[vacation_df["City"] == "Port Lincoln"]
vacation_stop1 = vacation_df.loc[vacation_df["City"] == "Murray Bridge"]
vacation_stop2 = vacation_df.loc[vacation_df["City"] == "Whyalla"] 
vacation_stop3 = vacation_df.loc[vacation_df["City"] == "Adelaide"] 

In [29]:
import numpy as np

In [30]:
vacation_start

City_ID          City Country  Max Temp Current Description      Lat  \
102      272  Port Lincoln      AU      72.0    scattered clouds -34.7333   

          Lng    Hotel Name  
102  135.8667  Port Lincoln

In [31]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.

# start location 
loc1 = vacation_start[["Lat", "Lng"]].to_numpy()
start =[]
for i in loc1:
    for u in i:
        start.append(u)
        
# End location
end = start
loc2 = vacation_end[["Lat", "Lng"]].to_numpy()
# end =[]
# for i in loc2:
#     for u in i:
#         end.append(u)
# stop 1 location
loc3 = vacation_stop1[["Lat", "Lng"]].to_numpy()
stop1 =[]
for i in loc3:
    for u in i:
        stop1.append(u)
        
# stop 2 location 
loc4 = vacation_stop2[["Lat", "Lng"]].to_numpy()
stop2 =[]
for i in loc4:
    for u in i:
        stop2.append(u)
        
# stop 3 location 
loc5 = vacation_stop3[["Lat", "Lng"]].to_numpy()
stop3=[]
for i in loc5:
    for u in i:
        stop3.append(u)
print(start)
print(end)
print(loc1)
print(loc2)
print(loc3)
print(loc4)

[-34.7333, 135.8667]
[-34.7333, 135.8667]
[[-34.7333 135.8667]]
[[-34.7333 135.8667]]
[[-35.1167 139.2667]]
[[-33.0333 137.5833]]


In [32]:
len(stop1)

2

In [33]:
import gmaps.datasets

In [34]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

# https://jupyter-gmaps.readthedocs.io/en/latest/tutorial.html#directions-layer
fig = gmaps.figure()
directions_layer = gmaps.directions_layer(
    start,
    end,
    waypoints = [stop1, stop2, stop3],
    travel_mode = 'DRIVING')
fig.add_layer(directions_layer)
fig


Figure(layout=FigureLayout(height='420px'))

In [35]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_end,vacation_stop1,vacation_stop2,vacation_stop3],ignore_index=True)
itinerary_df

City_ID           City Country  Max Temp Current Description      Lat  \
0      272   Port Lincoln      AU     72.00    scattered clouds -34.7333   
1      272   Port Lincoln      AU     72.00    scattered clouds -34.7333   
2      549  Murray Bridge      AU     90.82    scattered clouds -35.1167   
3      581        Whyalla      AU     80.17    scattered clouds -33.0333   
4      591       Adelaide      AU     90.55           clear sky -34.9333   

        Lng     Hotel Name  
0  135.8667   Port Lincoln  
1  135.8667   Port Lincoln  
2  139.2667  Murray Bridge  
3  137.5833        Whyalla  
4  138.6000       Adelaide

In [36]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [37]:
# 11a. Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))